server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: shen-picture-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shen_picture
    username: root
    password: 12345678
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
      db-config:
        logic-delete-field: delete
        logic-delete-value: 1
        logic-not-delete-value: 0
# 接口文档配置  http://localhost:8123/api/doc.html
knife4j:
  enable: true
  OpenAPI:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.chuanlong.shenpicturebackend.controller